// GENERATED by scripts/gen-news-images.py — do not edit by hand.
// Photographs from the publishers' own articles, keyed by bulletin item id.
// require() is resolved at build time, so a path in JSON cannot be required;
// the loader looks the id up here instead.

import type { ImageSourcePropType } from 'react-native';

export const NEWS_IMAGES: Record<string, ImageSourcePropType> = {
  "besiktas-avrupa-ligi-lig-asamasi": require('../assets/news/besiktas-avrupa-ligi-lig-asamasi.jpg'),
  "fatih-tekke-istifa-reddedildi": require('../assets/news/fatih-tekke-istifa-reddedildi.jpg'),
  "filenin-sultanlari-polonya-maci": require('../assets/news/filenin-sultanlari-polonya-maci.jpg'),
  "milliler-litvanya-eleme-maci": require('../assets/news/milliler-litvanya-eleme-maci.jpg'),
  "tour-of-istanbul-2026-rotasi": require('../assets/news/tour-of-istanbul-2026-rotasi.jpg'),
  "ucl-draw-gs-fb-2026": require('../assets/news/ucl-draw-gs-fb-2026.jpg'),
};
