#!/usr/bin/env python3
"""Generate src/strings.gen.ts from design/strings.json (flat English -> Turkish)."""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
SRC = ROOT / "design/strings.json"
OUT = ROOT / "mobile/src/strings.gen.ts"

data = json.loads(SRC.read_text())
lines = [
    "// GENERATED by scripts/gen-strings.py from design/strings.json — do not edit by hand.",
    "// Flat English -> Turkish map. The English string IS the key.",
    "",
    "export const TR: Record<string, string> = {",
]
for en, tr in data.items():
    lines.append(f"  {json.dumps(en, ensure_ascii=False)}: {json.dumps(tr, ensure_ascii=False)},")
lines += ["};", ""]
OUT.write_text("\n".join(lines))
print(f"{len(data)} strings -> {OUT.relative_to(ROOT)}")
