#!/usr/bin/env python3
"""Generate src/icons.gen.ts from design/assets/icons/*.svg (Phosphor, 0 0 256 256)."""
import re, pathlib, json

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
ICONS = ROOT / "design/assets/icons"
OUT = ROOT / "mobile/src/icons.gen.ts"

path_re = re.compile(r'<path fill="currentColor" d="([^"]*)"')

entries = {}
for f in sorted(ICONS.glob("*.svg")):
    ds = path_re.findall(f.read_text())
    if not ds:
        raise SystemExit(f"no path data in {f.name}")
    entries[f.stem] = ds

lines = [
    "// GENERATED by scripts/gen-icons.py from design/assets/icons/*.svg — do not edit by hand.",
    "// Phosphor (regular), viewBox 0 0 256 256, one path list per icon.",
    "",
    "export const ICON_PATHS = {",
]
for name, ds in entries.items():
    body = ", ".join(json.dumps(d) for d in ds)
    lines.append(f"  {json.dumps(name)}: [{body}],")
lines += [
    "} as const;",
    "",
    "export type IconName = keyof typeof ICON_PATHS;",
    "",
]
OUT.write_text("\n".join(lines))
print(f"{len(entries)} icons -> {OUT.relative_to(ROOT)}")
