#!/usr/bin/env python3
"""Copy the fetched news photographs into the app and generate their require map.

The bulletin's world items carry a photo from the publisher's article. React
Native resolves require() at build time, so a path held in JSON cannot be
required directly — this emits a static map from id to require() that the
loader indexes instead.

Photos are re-cut to 2x the widest slot they appear in (the story hero at 350pt),
because the originals come off news sites at 1200px or more and would otherwise
ship several megabytes of unused pixels.

    python3 scripts/gen-news-images.py
"""
import pathlib, shutil, sys
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
SRC = ROOT / "design/assets/news"
DST = ROOT / "mobile/assets/news"
OUT = ROOT / "mobile/src/generated/news-images.gen.ts"

WIDE = 700   # 350pt story hero at 2x
MIN_W = 400  # anything narrower than this is not worth showing

if not SRC.exists():
    sys.exit(f"no photos at {SRC.relative_to(ROOT)} — run the news fetch first")

DST.mkdir(parents=True, exist_ok=True)
for old in DST.glob("*.jpg"):
    old.unlink()

entries, skipped = [], []
for f in sorted(SRC.glob("*.jpg")):
    try:
        im = Image.open(f)
        im.load()
    except Exception as e:
        skipped.append(f"{f.name}: unreadable ({e})")
        continue
    if im.width < MIN_W:
        skipped.append(f"{f.name}: only {im.width}px wide")
        continue
    im = im.convert("RGB")
    if im.width > WIDE:
        im = im.resize((WIDE, round(im.height * WIDE / im.width)), Image.LANCZOS)
    im.save(DST / f.name, "JPEG", quality=82, optimize=True)
    entries.append(f.stem)

lines = [
    "// GENERATED by scripts/gen-news-images.py — do not edit by hand.",
    "// Photographs from the publishers' own articles, keyed by bulletin item id.",
    "// require() is resolved at build time, so a path in JSON cannot be required;",
    "// the loader looks the id up here instead.",
    "",
    "import type { ImageSourcePropType } from 'react-native';",
    "",
    "export const NEWS_IMAGES: Record<string, ImageSourcePropType> = {",
]
for stem in entries:
    lines.append(f"  {stem!r}: require('../../assets/news/{stem}.jpg'),".replace("'", '"', 2))
lines += ["};", ""]
OUT.write_text("\n".join(lines))

print(f"{len(entries)} photo(s) -> {OUT.relative_to(ROOT)}")
for s in skipped:
    print(f"  skipped {s}")
